name: CICD

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Clear Docker build cache
        run: docker builder prune -a -f
      - name: Build docker image
        run: docker build -t salsabilchedly14/projectspring10 --no-cache .
      - name: Publish image to docker hub
        run: docker push salsabilchedly14/projectspring10:latest
        
        
        
        